#!/usr/bin/env python3
"""
ITM SWO Trace Viewer
====================
PC 端接收 M487 SWO trace 資料並顯示

支援接收方式：
  1. UART-to-USB bridge (PB8 → FTDI/CH340 → USB)
  2. J-Link SWO (透過 J-Link Commander 或 RTT Viewer)
  3. File replay (離線分析)

ITM Protocol Reference:
  - ARM Cortex-M4 Technical Reference Manual
  - ARMv7-M Architecture Reference Manual (DDI0403E)
  - M487 Datasheet / User Manual

Usage:
  python itm_trace_viewer.py --uart COM5 --baud 2000000
  python itm_trace_viewer.py --file trace.bin
  python itm_trace_viewer.py --jlink
  python itm_trace_viewer.py --uart COM5 --color
"""

import sys
import os
import time
import struct
import argparse
import serial
import serial.tools.list_ports
from dataclasses import dataclass, field
from typing import Optional, List, Callable, Tuple
from enum import Enum, auto
import threading
import re

# ─────────────────────────────────────────────────────────────
# Console Colors (ANSI)
# ─────────────────────────────────────────────────────────────
class Col:
    RESET   = "\033[0m"
    BOLD    = "\033[1m"
    DIM     = "\033[2m"

    # Log levels
    ERR     = "\033[91m"   # Red
    WARN    = "\033[93m"   # Yellow
    INFO    = "\033[92m"   # Green
    DBG     = "\033[96m"   # Cyan
    TRC     = "\033[90m"   # Gray

    # Modules
    USB     = "\033[35m"   # Magenta
    MSC     = "\033[34m"   # Blue
    I2C     = "\033[33m"   # Orange
    HID     = "\033[36m"   # Teal

    TS      = "\033[90m"   # Gray timestamp
    HDR     = "\033[95m"   # Light magenta
    HEX     = "\033[94m"   # Blue hex
    ASCII   = "\033[92m"   # Green ASCII

NO_COLOR = os.environ.get("TERM") == "dumb" or sys.platform == "win32"

def c(color, text):
    """Wrap text with ANSI color (skip color on dumb terminals)."""
    if NO_COLOR or not hasattr(sys.stdout, "fileno"):
        return text
    return f"{color}{text}{Col.RESET}" if color else text

# ─────────────────────────────────────────────────────────────
# ITM Protocol
# ─────────────────────────────────────────────────────────────
# ITM over SWO uses TPIU (Trace Port Interface Unit) formatter.
# Each word from ITM stimulus ports is wrapped with a frame byte.
#
# TPIU Frame format (for sync mode / Manchester):
#   Bit 7:    1 = overflow / lost data, 0 = normal
#   Bit 6:    1 = error, 0 = normal
#   Bits[5:3]: Source ID (usually 000 = ITM)
#   Bits[2:0]: Low 3 bits of source Stimulus Port
#
#   If bit 0 of the 8-bit frame is 1 → this byte is a STIMULUS byte
#   The stimulus port is frame[3:0] | (<<3)
#
# Simple Async/NRZ mode (used by many debuggers):
#   Raw bytes are sent directly; no framing needed at byte level.
#
# Manchester encoding (TPIU Sync mode):
#   Each bit time contains a transition; baud = bit rate.
#   Actual ITM bytes are 4B/5B encoded by TPIU.
#
# For most practical purposes (J-Link, pyocd, UART bridge):
#   The raw byte stream from SWO contains ITM stimulus bytes
#   with the MSB encoding the source port.
#
# Simplified decoding used here:
#   - Bytes with bit 7=0 are treated as raw data characters
#   - Bytes with bit 7=1 are treated as extended source info
#   - The firmware uses ITM_STIM_PORT = 0, so all trace bytes
#     arrive with source port field indicating port 0

class ITMState(Enum):
    IDLE       = auto()
    IN_FRAME   = auto()
    IN_SYNC    = auto()

# ─────────────────────────────────────────────────────────────
# Packet Types
# ─────────────────────────────────────────────────────────────
@dataclass
class ITMStimulusPacket:
    """A single stimulus byte from an ITM port."""
    port:   int       # ITM stimulus port (0-31)
    data:   int       # 8-bit data
    ts_ns:  int = 0   # Timestamp in nanoseconds (if available)

    def char_data(self) -> str:
        if 32 <= self.data < 127:
            return chr(self.data)
        return f"\\x{self.data:02X}"

@dataclass
class ITMTimestamp:
    """ITM timestamp event (generated by DWT cycle counter)."""
    ts_ns:  int
    cycles: int = 0

@dataclass
class ITMSync:
    """ITM sync packet (indicates frame boundary)."""
    pass

# ─────────────────────────────────────────────────────────────
# ITM Parser
# ─────────────────────────────────────────────────────────────
class ITMParser:
    """
    Parse raw SWO byte stream into ITM packets.

    Handles:
    - TPIU frame removal
    - Stimulus port demultiplexing
    - Timestamp extraction
    - Line reconstruction
    """

    def __init__(self, port_filter: Optional[int] = None):
        """
        Args:
            port_filter: Only show packets from this port (None = all ports)
        """
        self.port_filter = port_filter
        self._pkt_buf: List[ITMStimulusPacket] = []
        self._byte_accum: List[int] = []
        self._frame_buf: bytearray = bytearray()
        self._last_ts_ns: int = 0
        self._local_cycle_cnt: int = 0

        # ITM TPIU frame constants
        self._TPIU_FSYNC_MIN  = 0x80  # Frame sync prefix
        self._TPIU_FRAME_MASK = 0x07
        self._TPIU_SRC_SHIFT  = 3
        self._TPIU_STIM_VALID = 0x80  # Stimulus valid bit

        # Known sync sequences
        self._sync_known = bytes([0x00, 0x00, 0x00, 0x00, 0x80])

        # Trace state
        self._byte_count: int = 0
        self._lost_bytes: int = 0
        self._pkt_count: int = 0

    def parse_byte(self, b: int) -> List[object]:
        """
        Parse a single byte from the SWO stream.
        Returns a list of ITM objects (packets, timestamps, etc.)
        """
        out: List[object] = []
        self._byte_count += 1

        # Check for TPIU frame sync (0x80 followed by 0x00)
        if b == 0x80:
            self._frame_buf.clear()
            self._frame_buf.append(b)
            return out

        if self._frame_buf:
            self._frame_buf.append(b)
            # Check for complete sync frame
            if len(self._frame_buf) >= 5:
                self._frame_buf.clear()
                out.append(ITMSync())
                return out
            elif b != 0x00 and len(self._frame_buf) >= 2:
                # Not a valid sync frame, treat first byte as data
                # The 0x80 prefix is a frame sync marker
                self._frame_buf.clear()
                # Treat remaining bytes as raw
                for leftover in self._frame_buf:
                    sub = self._parse_raw_byte(leftover)
                    if sub:
                        out.extend(sub)
                self._frame_buf.clear()
            return out

        # Check for Manchester/Async 4B/5B sync patterns
        if self._byte_count <= 5 and b == 0x00:
            return out  # Skip leading zeros

        sub = self._parse_raw_byte(b)
        if sub:
            out.extend(sub)
        return out

    def _parse_raw_byte(self, b: int) -> List[object]:
        """Parse a raw byte as a potential ITM stimulus."""
        out: List[object] = []

        # ITM 8-bit Stimulus encoding:
        # The ITM sends one byte per stimulus port write.
        # At the TPIU level, the byte is framed with source info.
        #
        # Common simple format: raw bytes without framing (async UART mode)
        # In this case, every byte is a stimulus byte from port 0.
        #
        # Framed format (TPIU):
        #   bit 7 = 1: stimulus port info valid (bits 6:3 = source, bits 2:0 = port low)
        #   bit 7 = 0: just a regular byte
        #
        # For firmware using ITM_STIM_PORT=0 and simple SWO output,
        # we see raw ASCII characters and \\n for newlines.

        # Simple case: raw byte mode (no framing)
        # If b looks like printable ASCII or control char, treat as stimulus
        port = 0  # Default to port 0 (firmware uses this)

        if self.port_filter is not None and port != self.port_filter:
            return out

        pkt = ITMStimulusPacket(port=port, data=b, ts_ns=self._last_ts_ns)
        self._pkt_count += 1
        out.append(pkt)
        return out

    def parse_bytes(self, data: bytes) -> List[object]:
        """Parse a byte buffer."""
        out: List[object] = []
        for b in data:
            out.extend(self.parse_byte(b))
        return out

    @property
    def stats(self) -> dict:
        return {
            "bytes": self._byte_count,
            "packets": self._pkt_count,
            "lost": self._lost_bytes,
        }

# ─────────────────────────────────────────────────────────────
# Line Buffer (reconstructs lines from stimulus bytes)
# ─────────────────────────────────────────────────────────────
class LineBuffer:
    """Reconstruct complete lines from ITM stimulus bytes."""

    def __init__(self, max_line: int = 1024):
        self.buf = bytearray()
        self.max_line = max_line
        self._last_ts = ""

    def push(self, pkt: ITMStimulusPacket) -> Optional[Tuple[str, str, Optional[ITMStimulusPacket]]]:
        """
        Add a byte to the buffer.
        Returns (timestamp_str, line_str, last_byte) when a complete line is available,
        or None if line is incomplete.
        """
        if pkt.data == ord('\n'):
            # Complete line
            try:
                line = bytes(self.buf).decode('utf-8', errors='replace')
            except Exception:
                line = bytes(self.buf).hex(' ')
            ts = self._last_ts

            # Keep partial (no \\r)
            if line.endswith('\r'):
                line = line[:-1]

            self.buf.clear()
            return (ts, line, pkt)
        elif pkt.data == ord('\r'):
            # \\r\\n line ending
            if self.buf:
                try:
                    line = bytes(self.buf).decode('utf-8', errors='replace')
                except Exception:
                    line = bytes(self.buf).hex(' ')
                self.buf.clear()
                return (self._last_ts, line, pkt)
            return None
        else:
            if len(self.buf) < self.max_line:
                self.buf.append(pkt.data)
            return None

    def flush(self) -> Optional[Tuple[str, str, None]]:
        """Return any remaining content in buffer."""
        if self.buf:
            try:
                line = bytes(self.buf).decode('utf-8', errors='replace')
            except Exception:
                line = bytes(self.buf).hex(' ')
            self.buf.clear()
            return (self._last_ts, line, None)
        return None

# ─────────────────────────────────────────────────────────────
# Output Formatter
# ─────────────────────────────────────────────────────────────
class OutputFormatter:
    """Format and colorize ITM output for console."""

    def __init__(self, use_color: bool = True, show_hex: bool = False,
                 show_timestamps: bool = True, show_stats: bool = False):
        self.use_color     = use_color
        self.show_hex      = show_hex
        self.show_ts       = show_timestamps
        self.show_stats    = show_stats
        self._line_count   = 0
        self._parser: Optional[ITMParser] = None

        # ANSI color map
        self._c = {
            "err":   Col.ERR,
            "warn":  Col.WARN,
            "info":  Col.INFO,
            "dbg":   Col.DBG,
            "ts":    Col.TS,
            "reset": Col.RESET,
        }

    def _color(self, key: str, text: str) -> str:
        if not self.use_color:
            return text
        return f"{self._c[key]}{text}{self._c['reset']}"

    def _detect_level(self, line: str) -> str:
        """Detect log level from line content."""
        upper = line.upper()
        if "[ERR"  in upper or " ERR" in upper: return "err"
        if "[WARN" in upper or " WARN" in upper: return "warn"
        if "[INFO" in upper or " INFO" in upper: return "info"
        if "[DBG"  in upper or " DBG" in upper:  return "dbg"
        if "[TRC"  in upper or " TRC" in upper:  return "dbg"  # trace → dbg color
        return "info"

    def _detect_module(self, line: str) -> str:
        """Detect module from line content and return color."""
        upper = line.upper()
        if "[USB]" in upper:  return Col.USB
        if "[MSC]" in upper:  return Col.MSC
        if "[I2C]" in upper:  return Col.I2C
        if "[HID]" in upper:  return Col.HID
        return ""

    def print_line(self, ts: str, line: str, last_pkt: Optional[ITMStimulusPacket] = None):
        """Print a complete log line with optional colorization."""
        self._line_count += 1

        level_color = self._detect_level(line)
        module_color = self._detect_module(line)

        # Timestamp
        if self.show_ts and ts:
            ts_out = self._color("ts", f"[{ts}]")
        else:
            ts_out = ""

        # Level color tag
        tag = ""
        if level_color == "err":
            tag = self._color("err", " ✗")
        elif level_color == "warn":
            tag = self._color("warn", " ⚠")
        elif level_color == "info":
            tag = self._color("info", " ℹ")
        elif level_color == "dbg":
            tag = self._color("dbg", " ◷")

        # Module color
        if module_color:
            line_out = f"{module_color}{line}{Col.RESET if self.use_color else ''}"
        else:
            line_out = line

        # Assemble
        parts = [x for x in [ts_out, tag, line_out] if x]
        print(" ".join(parts))

        # Show hex dump for non-printable content
        if self.show_hex and last_pkt:
            try:
                hex_str = " ".join(f"{b:02X}" for b in line.encode('utf-8', errors='replace'))
            except Exception:
                hex_str = "???"
            print(self._color("ts", f"    HEX: {hex_str}"))

    def print_raw(self, data: bytes):
        """Print raw hex dump."""
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            hex_str = " ".join(f"{b:02X}" for b in chunk)
            ascii_str = "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)
            print(f"  {i:04X}: {hex_str:<48}  {ascii_str}")

    def print_stats(self, parser: 'ITMParser'):
        """Print parser statistics."""
        s = parser.stats
        print(self._color("ts",
            f"[ITM Stats] bytes={s['bytes']} packets={s['packets']} lost={s['lost']}"))

    def print_welcome(self, args):
        """Print startup banner."""
        print(c(Col.HDR, "═" * 60))
        print(c(Col.HDR, "  ITM SWO Trace Viewer  (M487 Cortex-M4)"))
        print(c(Col.HDR, "═" * 60))
        mode = "unknown"
        if args.get("uart"):
            mode = f"UART {args['uart']} @ {args.get('baud', 2000000)} baud"
        elif args.get("file"):
            mode = f"File: {args['file']}"
        elif args.get("jlink"):
            mode = "J-Link SWO"
        print(f"  Mode  : {mode}")
        print(f"  Filter: port={args.get('port', 'all')}")
        print(f"  Color : {args.get('color', True)}")
        print(c(Col.HDR, "─" * 60))
        print(c(Col.DIM,  "  Press Ctrl+C to exit..."))
        print(c(Col.HDR, "═" * 60) + "\n")

# ─────────────────────────────────────────────────────────────
# Data Receivers (Input Sources)
# ─────────────────────────────────────────────────────────────
class ReceiverBase:
    """Abstract base for data receivers."""

    def __init__(self):
        self._running = False

    def start(self):
        self._running = True

    def stop(self):
        self._running = False

    def readinto(self, buf: bytearray) -> int:
        """Read into buffer, return number of bytes read (0 = no data, -1 = EOF/error)."""
        raise NotImplementedError

    def is_active(self) -> bool:
        return self._running

class UARTReceiver(ReceiverBase):
    """
    Receive SWO data via UART-to-USB bridge.
    M487 PB8 (SWO) → UART-to-USB (FTDI/CH340/etc) → USB → PC

    Common UART-to-USB connections:
      - FTDI FT232R / FT230X
      - WCH CH340
      - Silabs CP2102

    UART settings for SWO:
      - Baud: 115200 ~ 2000000 (match TPI/ITM configuration)
      - Data bits: 8
      - Parity: None
      - Stop bits: 1
      - Flow control: None
    """

    def __init__(self, port: str, baud: int = 2000000,
                 timeout: float = 1.0):
        super().__init__()
        self.port = port
        self.baud = baud
        self.timeout = timeout
        self._ser: Optional[serial.Serial] = None
        self._buf = bytearray(4096)

    def _open(self):
        """Open serial port."""
        try:
            self._ser = serial.Serial(
                port=self.port,
                baudrate=self.baud,
                bytesize=serial.EIGHTBITS,
                parity=serial.PARITY_NONE,
                stopbits=serial.STOPBITS_ONE,
                timeout=self.timeout,
                xonxoff=False,
                rtscts=False,
                dsrdtr=False,
            )
            # Clear buffers
            self._ser.reset_input_buffer()
            self._ser.reset_output_buffer()
            print(f"[UART] Opened {self.port} @ {self.baud} baud")
            return True
        except serial.SerialException as e:
            print(f"[UART] Failed to open {self.port}: {e}")
            return False

    def start(self):
        if not self._open():
            return
        super().start()

    def stop(self):
        super().stop()
        if self._ser and self._ser.is_open:
            try:
                self._ser.close()
                print("[UART] Port closed")
            except Exception:
                pass

    def readinto(self, buf: bytearray) -> int:
        """Read available bytes into buf. Returns count or -1 on error."""
        if not self._ser or not self._ser.is_open:
            return -1
        try:
            # Read up to len(buf) bytes with short timeout
            data = self._ser.read(len(buf))
            n = len(data)
            if n > 0:
                buf[:n] = data
            return n
        except serial.SerialException as e:
            print(f"[UART] Read error: {e}")
            return -1

    @staticmethod
    def list_ports() -> List[Tuple[str, str]]:
        """List available COM ports with descriptions."""
        ports = serial.tools.list_ports.comports()
        return [(p.device, p.description or "Unknown") for p in ports]


class FileReceiver(ReceiverBase):
    """
    Read SWO data from a recorded binary file.
    Useful for offline analysis and testing.
    """

    def __init__(self, path: str, loop: bool = False):
        super().__init__()
        self.path = path
        self.loop = loop
        self._f: Optional[object] = None

    def start(self):
        try:
            self._f = open(self.path, "rb")
            print(f"[File] Opened {self.path}")
        except OSError as e:
            print(f"[File] Cannot open {self.path}: {e}")

    def stop(self):
        super().stop()
        if self._f:
            self._f.close()

    def readinto(self, buf: bytearray) -> int:
        """Read from file. Returns 0 when EOF (and loops if enabled)."""
        if not self._f:
            return -1
        try:
            data = self._f.read(len(buf))
            n = len(data)
            if n > 0:
                buf[:n] = data
                return n
            elif self.loop:
                self._f.seek(0)
                return self.readinto(buf)  # Tail-recurse
            else:
                return 0  # EOF
        except OSError as e:
            print(f"[File] Read error: {e}")
            return -1


class JLinkReceiver(ReceiverBase):
    """
    Receive SWO data via SEGGER J-Link.
    Requires J-Link software installed and J-Link hardware connected.

    Uses J-Link Commander or J-Link SWO Viewer via subprocess.
    SWO data is captured and piped to this process via stdio or temp file.

    Alternative: Use pyocd with CMSIS-DAP debuggers that support SWO.
    """

    def __init__(self, jlink_script: Optional[str] = None,
                 device: str = "M487", speed: int = 4000):
        super().__init__()
        self.jlink_script = jlink_script
        self.device = device
        self.speed = speed
        self._proc: Optional[object] = None
        self._pipe: Optional[object] = None

    def start(self):
        """Try to start J-Link SWO capture."""
        # Try J-Link Commander approach
        # JLinkSWOViewer -Device {device} -Speed {speed} -If SWD -SWOBr 2000000
        jlink_exe = os.environ.get("JLINK_PATH", "JLinkSWOViewer")
        print(f"[JLink] Attempting J-Link SWO capture (device={self.device}, speed={self.speed})")
        print(f"[JLink] J-Link path: {jlink_exe}")
        print("[JLink] If J-Link is not available, use --uart mode with a UART-to-USB bridge.")
        print("[JLink] For J-Link: Install J-Link software from https://www.segger.com/downloads/j-link/")
        # Cannot actually capture without J-Link hardware
        # This is a placeholder that explains how to use J-Link
        self._running = False

    def stop(self):
        super().stop()

    def readinto(self, buf: bytearray) -> int:
        return 0  # No data


class StdinReceiver(ReceiverBase):
    """
    Read SWO data from stdin.
    Useful for piping from other tools.
    """

    def __init__(self):
        super().__init__()

    def start(self):
        super().start()
        print("[Stdin] Reading SWO data from stdin...")

    def readinto(self, buf: bytearray) -> int:
        try:
            data = sys.stdin.buffer.read(len(buf))
            n = len(data)
            if n > 0:
                buf[:n] = data
                return n
            return 0
        except Exception:
            return -1

# ─────────────────────────────────────────────────────────────
# ITM Viewer (Main Controller)
# ─────────────────────────────────────────────────────────────
class ITMViewer:
    """
    Main ITM Trace Viewer.
    Coordinates receiver, parser, and output.
    """

    def __init__(self, receiver: ReceiverBase,
                 formatter: OutputFormatter,
                 parser: ITMParser,
                 recv_buf_size: int = 4096):
        self.receiver  = receiver
        self.formatter  = formatter
        self.parser     = parser
        self.buf_size   = recv_buf_size
        self._recv_buf  = bytearray(recv_buf_size)
        self._line_buf  = LineBuffer()
        self._start_time = time.monotonic()
        self._running    = False
        self._print_lock = threading.Lock()

    def run(self, duration: Optional[float] = None):
        """
        Run the viewer loop.

        Args:
            duration: Run for this many seconds (None = run forever)
        """
        self.receiver.start()
        self._running = True
        self._start_time = time.monotonic()

        print("[Viewer] Starting trace capture loop...")

        try:
            while self._running:
                # Check duration
                if duration and (time.monotonic() - self._start_time) >= duration:
                    break

                # Read from receiver
                n = self.receiver.readinto(self._recv_buf)
                if n < 0:
                    print("[Viewer] Receiver error, stopping.")
                    break
                if n == 0:
                    time.sleep(0.01)  # Brief sleep when no data
                    continue

                # Parse received bytes
                data = bytes(self._recv_buf[:n])
                packets = self.parser.parse_bytes(data)

                # Output packets
                self._process_packets(packets)

        except KeyboardInterrupt:
            print("\n[Viewer] Interrupted by user.")
        finally:
            self.stop()

    def _process_packets(self, packets: List[object]):
        """Process parsed ITM packets."""
        for pkt in packets:
            if isinstance(pkt, ITMSync):
                # Sync packet - could log but usually not shown
                continue

            if isinstance(pkt, ITMTimestamp):
                ts_str = f"{pkt.ts_ns / 1e6:.3f}"
                self._line_buf._last_ts = ts_str
                continue

            if isinstance(pkt, ITMStimulusPacket):
                result = self._line_buf.push(pkt)
                if result:
                    ts_str, line_str, last_pkt = result
                    with self._print_lock:
                        self.formatter.print_line(ts_str, line_str, last_pkt)

        # Flush partial line on timeout/sync
        if isinstance(packets[-1], ITMSync) if packets else False:
            result = self._line_buf.flush()
            if result:
                ts_str, line_str, _ = result
                with self._print_lock:
                    self.formatter.print_line(ts_str, line_str, None)

    def stop(self):
        """Stop the viewer."""
        self._running = False
        self.receiver.stop()

        # Flush any remaining buffer
        result = self._line_buf.flush()
        if result:
            ts_str, line_str, _ = result
            self.formatter.print_line(ts_str, line_str, None)

        # Show stats
        if self.formatter.show_stats:
            self.formatter.print_stats(self.parser)

        elapsed = time.monotonic() - self._start_time
        print(f"\n[Viewer] Stopped. Elapsed: {elapsed:.1f}s")

# ─────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────
def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="ITM SWO Trace Viewer for M487 Cortex-M4",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  UART bridge (M487 PB8 → FTDI → USB):
    python itm_trace_viewer.py --uart COM5 --baud 2000000

  List available COM ports:
    python itm_trace_viewer.py --list-ports

  File replay:
    python itm_trace_viewer.py --file trace.bin

  With color disabled:
    python itm_trace_viewer.py --uart COM5 --no-color

  Show hex dump:
    python itm_trace_viewer.py --uart COM5 --hex
        """
    )

    # Input modes (mutually exclusive, except --list-ports can override)
    mode = p.add_mutually_exclusive_group()
    mode.add_argument("--uart",   dest="uart",   metavar="PORT",
                      help="UART port (e.g. COM5, /dev/ttyUSB0)")
    mode.add_argument("--file",   dest="file",   metavar="FILE",
                      help="Read from binary trace file")
    mode.add_argument("--stdin",  dest="stdin",  action="store_true",
                      help="Read from stdin (pipe from other tools)")
    mode.add_argument("--jlink",  dest="jlink",  action="store_true",
                      help="Use J-Link SWO capture (requires J-Link hardware)")

    # UART options
    p.add_argument("--baud",  dest="baud",  type=int, default=2000000,
                   help="UART baud rate (default: 2000000 for 2MHz SWO)")
    p.add_argument("--list-ports", dest="list_ports", action="store_true",
                   help="List available COM ports")

    # Parser options
    p.add_argument("--port",  dest="port",  type=int, default=None,
                   help="Filter by ITM stimulus port (0-31, default: all)")

    # Output options
    p.add_argument("--no-color",   dest="color",   action="store_false", default=True,
                   help="Disable ANSI color output")
    p.add_argument("--hex",        dest="hex",      action="store_true",
                   help="Show hex dump of each line")
    p.add_argument("--no-ts",      dest="ts",       action="store_false", default=True,
                   help="Hide timestamps")
    p.add_argument("--stats",      dest="stats",    action="store_true",
                   help="Show parser statistics on exit")
    p.add_argument("--loop",       dest="loop",     action="store_true",
                   help="Loop file playback (for --file mode)")

    # Timing
    p.add_argument("--duration",  dest="duration",  type=float, default=None,
                   help="Run for N seconds then exit")

    # J-Link options
    p.add_argument("--jlink-device", dest="jlink_device", default="M487",
                   help="J-Link device name (default: M487)")
    p.add_argument("--jlink-speed",  dest="jlink_speed",  type=int, default=4000,
                   help="J-Link SWD speed in kHz (default: 4000)")

    return p


def list_serial_ports():
    """List available serial ports."""
    ports = UARTReceiver.list_ports()
    if not ports:
        print("No COM ports found.")
        return
    print("Available COM ports:")
    for device, desc in ports:
        print(f"  {device:10s}  {desc}")


def main():
    p = build_parser()
    args = p.parse_args()

    # List ports mode
    if args.list_ports:
        list_serial_ports()
        return

    # Require at least one input mode
    if not any([args.uart, args.file, args.stdin, args.jlink]):
        p.error("one of --uart, --file, --stdin, or --jlink is required (or use --list-ports)")

    # Detect color support
    color = args.color and not NO_COLOR and sys.stdout.isatty()

    # Build formatter
    formatter = OutputFormatter(
        use_color=color,
        show_hex=args.hex,
        show_timestamps=args.ts,
        show_stats=args.stats,
    )

    # Build parser
    parser = ITMParser(port_filter=args.port)

    # Build receiver
    if args.uart:
        receiver = UARTReceiver(args.uart, baud=args.baud)
    elif args.file:
        receiver = FileReceiver(args.file, loop=args.loop)
    elif args.stdin:
        receiver = StdinReceiver()
    elif args.jlink:
        receiver = JLinkReceiver(device=args.jlink_device, speed=args.jlink_speed)
    else:
        p.error("No input mode specified")
        return

    # Build viewer
    args_dict = {
        "uart": getattr(args, "uart", None),
        "file": getattr(args, "file", None),
        "jlink": getattr(args, "jlink", None),
        "baud": args.baud,
        "port": args.port,
        "color": color,
    }
    formatter.print_welcome(args_dict)

    viewer = ITMViewer(receiver, formatter, parser)

    # Run
    viewer.run(duration=args.duration)


if __name__ == "__main__":
    main()
