/*
 * M487FilterMof.h
 *
 * AUTO-GENERATED HEADER from M487Filter.mof
 * This file is normally generated by the WDK build process (mofcomp/wmimofck).
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * To regenerate:
 *   1. Compile M487Filter.mof with mofcomp:
 *      mofcomp -B M487FilterMof.dll M487Filter.mof
 *   2. Or use Wmimofck.exe during build
 *
 * The GUIDs and structure definitions below are placeholders for the
 * MOF-defined class M487FilterDeviceInformation.
 */

#ifndef _M487_FILTER_MOF_H
#define _M487_FILTER_MOF_H

//
// GUID: {C8E5F3B0-E8C4-4F7A-9A3D-7B2C4E1F5A9D}
//
DEFINE_GUID(
    M487FilterDeviceInformation_GUID,
    0xC8E5F3B0, 0xE8C4, 0x4F7A, 0x9A, 0x3D, 0x7B, 0x2C, 0x4E, 0x1F, 0x5A, 0x9D);

//
// M487FilterDeviceInformation data block
//
typedef struct _M487FilterDeviceInformation
{
    //
    // [key, read] string InstanceName;
    // (Key field - handled by WMI framework, not included in buffer)
    //

    //
    // [read] boolean Active;
    //
    BOOLEAN Active;

    //
    // [WmiDataId(1), read, write] boolean PassThroughEnabled;
    //
    BOOLEAN PassThroughEnabled;

    //
    // [WmiDataId(2), read] boolean CaptureEnabled;
    //
    BOOLEAN CaptureEnabled;

} M487FilterDeviceInformation, *PM487FilterDeviceInformation;

//
// WMI data item IDs
//
#define M487FilterDeviceInformation_Active_OFFSET          0
#define M487FilterDeviceInformation_Active_SIZE           1
#define M487FilterDeviceInformation_Active_SIZE_IS_AT_LEAST

#define M487FilterDeviceInformation_PassThroughEnabled_OFFSET  1
#define M487FilterDeviceInformation_PassThroughEnabled_SIZE    1
#define M487FilterDeviceInformation_PassThroughEnabled_SIZE_IS_AT_LEAST

#define M487FilterDeviceInformation_CaptureEnabled_OFFSET  2
#define M487FilterDeviceInformation_CaptureEnabled_SIZE    1
#define M487FilterDeviceInformation_CaptureEnabled_SIZE_IS_AT_LEAST

//
// M487FilterRingBufferInfo - Ring buffer status via WMI
// GUID: {D4E5F6A7-8C9D-4B5A-B3C2-1E0F2A3B4C5D}
//
DEFINE_GUID(
    M487FilterRingBufferInfo_GUID,
    0xD4E5F6A7, 0x8C9D, 0x4B5A, 0xB3, 0xC2, 0x1E, 0x0F, 0x2A, 0x3B, 0x4C, 0x5D);

typedef struct _M487FilterRingBufferInfo
{
    //
    // [WmiDataId(1), read] uint64 RingBufferPhysicalAddress;
    //
    ULONGLONG RingBufferPhysicalAddress;

    //
    // [WmiDataId(2), read] uint32 RingBufferSize;
    //
    ULONG RingBufferSize;

    //
    // [WmiDataId(3), read] uint64 TotalCaptured;
    //
    ULONGLONG TotalCaptured;

    //
    // [WmiDataId(4), read] uint32 DroppedCount;
    //
    ULONG DroppedCount;

    //
    // [WmiDataId(5), read] uint32 CurrentUsedSlots;
    //
    ULONG CurrentUsedSlots;

    //
    // [WmiDataId(6), read] uint32 TotalSlots;
    //
    ULONG TotalSlots;

    //
    // [WmiDataId(7), read] uint32 SlotSize;
    //
    ULONG SlotSize;

    //
    // [WmiDataId(8), read] boolean RingInitialized;
    //
    BOOLEAN RingInitialized;

} M487FilterRingBufferInfo, *PM487FilterRingBufferInfo;

//
// M487FilterInterceptConfig - Interception configuration via WMI
// GUID: {E5F6A7B8-9D8C-5A4B-C3D2-0F1E2A3B4C5D}
//
DEFINE_GUID(
    M487FilterInterceptConfigWmi_GUID,
    0xE5F6A7B8, 0x9D8C, 0x5A4B, 0xC3, 0xD2, 0x0F, 0x1E, 0x2A, 0x3B, 0x4C, 0x5D);

typedef struct _M487FilterInterceptConfigWmi
{
    //
    // [WmiDataId(1), read, write] boolean CaptureSetFeature;
    //
    BOOLEAN CaptureSetFeature;

    //
    // [WmiDataId(2), read, write] boolean CaptureGetFeature;
    //
    BOOLEAN CaptureGetFeature;

    //
    // [WmiDataId(3), read, write] boolean CaptureWriteReport;
    //
    BOOLEAN CaptureWriteReport;

    //
    // [WmiDataId(4), read, write] boolean CaptureReadReport;
    //
    BOOLEAN CaptureReadReport;

} M487FilterInterceptConfigWmi, *PM487FilterInterceptConfigWmi;

//
// WMI data item IDs for M487FilterInterceptConfigWmi
//
#define M487FilterInterceptConfigWmi_CaptureSetFeature_OFFSET   0
#define M487FilterInterceptConfigWmi_CaptureSetFeature_SIZE      1
#define M487FilterInterceptConfigWmi_CaptureGetFeature_OFFSET    1
#define M487FilterInterceptConfigWmi_CaptureGetFeature_SIZE     1
#define M487FilterInterceptConfigWmi_CaptureWriteReport_OFFSET   2
#define M487FilterInterceptConfigWmi_CaptureWriteReport_SIZE    1
#define M487FilterInterceptConfigWmi_CaptureReadReport_OFFSET   3
#define M487FilterInterceptConfigWmi_CaptureReadReport_SIZE     1

//
// Data item IDs (used in WMI SetItem)
//
#define M487FilterInterceptConfigWmi_SetFeature_ID   1
#define M487FilterInterceptConfigWmi_GetFeature_ID    2
#define M487FilterInterceptConfigWmi_WriteReport_ID  3
#define M487FilterInterceptConfigWmi_ReadReport_ID   4

#endif // _M487_FILTER_MOF_H
